sudo: false
dist: xenial
language: python
cache: pip

python:
  - 3.6.3
  - 3.7.2

install:
  - pip install -Ur dev-requirements.txt
script:
  - make flake8
  - make stylecheck

notifications:
  email: false
